### ISSUE TITLE
Explain Gulp version pinning

### ISSUE THREAD

**Issue by iamtew** [magneticio/vamp-ui#192]
Please provide an explanation for why we use `gulpjs/gulp#4.0` and not the normal master branch of gulp.

- https://github.com/magneticio/vamp-ui/blob/f28f9e5093ab5475b96e4572d3e5da1f9a1769b1/.travis.yml#L4
- https://github.com/magneticio/vamp-ui/blob/master/README.md

**Comment by iamtew** [comment]
```bash
[root@vamp-buildserver vamp-ui]# gulp build
[13:52:32] Loading /srv/src/vamp-ui/gulp_tasks/browsersync.js
[13:52:32] Loading /srv/src/vamp-ui/gulp_tasks/build.js
[13:52:33] Loading /srv/src/vamp-ui/gulp_tasks/inject.js
[13:52:33] Loading /srv/src/vamp-ui/gulp_tasks/karma.js
[13:52:33] Loading /srv/src/vamp-ui/gulp_tasks/misc.js
[13:52:33] Loading /srv/src/vamp-ui/gulp_tasks/partials.js
[13:52:33] Loading /srv/src/vamp-ui/gulp_tasks/scripts.js
[13:52:33] Loading /srv/src/vamp-ui/gulp_tasks/styles.js
[13:52:34] Using gulpfile /srv/src/vamp-ui/gulpfile.js
/usr/local/nvm/versions/node/v7.2.1/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/nvm/versions/node/v7.2.1/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
[root@vamp-buildserver vamp-ui]# node --version 
v7.2.1
[root@vamp-buildserver vamp-ui]# gulp --version
[13:53:00] CLI version 3.9.1
[13:53:00] Local version 4.0.0-alpha.2
[root@vamp-buildserver vamp-ui]# ./node_modules/.bin/gulp build
[13:53:10] Loading /srv/src/vamp-ui/gulp_tasks/browsersync.js
[13:53:10] Loading /srv/src/vamp-ui/gulp_tasks/build.js
[13:53:10] Loading /srv/src/vamp-ui/gulp_tasks/inject.js
[13:53:10] Loading /srv/src/vamp-ui/gulp_tasks/karma.js
[13:53:11] Loading /srv/src/vamp-ui/gulp_tasks/misc.js
[13:53:11] Loading /srv/src/vamp-ui/gulp_tasks/partials.js
[13:53:11] Loading /srv/src/vamp-ui/gulp_tasks/scripts.js
[13:53:11] Loading /srv/src/vamp-ui/gulp_tasks/styles.js
[13:53:11] Using gulpfile /srv/src/vamp-ui/gulpfile.js
[13:53:11] Starting 'build'...
[13:53:11] Starting 'partials'...
[13:53:11] Finished 'partials' after 85 ms
[13:53:11] Starting 'inject'...
[13:53:11] Starting 'other'...
[13:53:11] Starting 'failAfterError'...
[13:53:11] Starting 'styles'...
[13:53:11] Starting 'scripts'...
[13:53:12] Finished 'styles' after 535 ms
[13:53:13] Finished 'other' after 1.59 s
[13:53:13] Finished 'failAfterError' after 1.73 s
[13:53:13] Finished 'scripts' after 1.72 s
[13:53:13] Starting 'inject'...
[13:53:13] gulp-inject 35 files into index.html.
[13:53:13] Finished 'inject' after 162 ms
[13:53:13] Finished 'inject' after 1.89 s
[13:53:13] Starting 'build'...
[13:53:13] gulp-inject 1 files into index.html.
[13:53:28] Finished 'build' after 15 s
[13:53:28] Starting 'fixDist'...
[13:53:28] Finished 'fixDist' after 9.75 ms
[13:53:28] Finished 'build' after 17 s
```

**Comment by brniamut** [comment]
I will write it down as a documentation page.

Vamp is being build using gulp. The version of gulp that should be used is 4! This is because the in the gulpfile we use a gulpInstance variable which opens up the possibility to do actions based on the runtime state. Because the core of vamp-ui was created using yeoman the gulpfile still reflects this.
